<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Gridaddeditdelete.aspx.cs" Inherits="Emailsent.Gridaddeditdelete" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="Gender" HeaderText="Gender" SortExpression="Gender" />
                <asp:BoundField DataField="Contactno" HeaderText="Contactno" SortExpression="Contactno" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                <asp:BoundField DataField="Location" HeaderText="Location" SortExpression="Location" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:TableConnectionString %>" SelectCommand="SELECT [Id], [Name], [Gender], [Contactno], [Email], [Password], [Location] FROM [Registrationform]" UpdateCommand="Update [Registrationform] set [Name]=@Name, [Gender]=@Gender, [Contactno]=@Contactno, [Email]=@Email, [Password]=@Password, [Location]=@Location where Id=@Id" DeleteCommand="Delete from [Registrationform] where [Id]=@Id"></asp:SqlDataSource>
    <br />
        <br />

        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
        <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
        <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
        <asp:TextBox ID="TextBox4" runat="server"></asp:TextBox>
        <asp:TextBox ID="TextBox5" runat="server"></asp:TextBox>
        <asp:TextBox ID="TextBox6" runat="server"></asp:TextBox>
        <asp:Button ID="Button1" runat="server" Text="Add Fields" OnClick="Button1_Click" />
    </div>
    </form>
</body>
</html>
